In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('HR_comma_sep.csv')
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

In [47]:
df_encoded = pd.get_dummies(df, columns=['salary'], drop_first=True)

In [35]:
df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]
subdf.head()

   satisfaction_level  average_montly_hours  promotion_last_5years  salary
0                0.38                   157                      0     low
1                0.80                   262                      0  medium
2                0.11                   272                      0  medium
3                0.72                   223                      0     low
4                0.37                   159                      0     low

In [61]:
x = df_encoded[['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 
                'salary_medium', 'salary_high']]  # Adjust column names as needed

y = df_encoded['left']

KeyError: "['salary_high'] not in index"

In [51]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3)

In [55]:
from sklearn.linear_model import LogisticRegression

In [57]:
model = LogisticRegression()
model.fit(X_train,Y_train)

ValueError: could not convert string to float: 'low'